export const workItems = [
  {
    id: "1",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1jERD51LWV6-vZPjhqWCZtd9cm219wJsB",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1jERD51LWV6-vZPjhqWCZtd9cm219wJsB",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "animation",
    subcategory: "Clay Art",
  },
  {
    id: "2",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_tNqmNsOhDZ7koQDOOdfQTiYvWlQmXQl",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_tNqmNsOhDZ7koQDOOdfQTiYvWlQmXQl",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Clay Art",
  },
  {
    id: "3",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_z0CnZOCmdo9HksF2R05IP400yKiHWOW",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_z0CnZOCmdo9HksF2R05IP400yKiHWOW",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Clay Art",
  },
  {
    id: "4",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_uyT-TsQ61ffBA2JNbfqZpeGGqX2KCyX",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_uyT-TsQ61ffBA2JNbfqZpeGGqX2KCyX",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Clay Art",
  },
  {
    id: "5",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZwwxemHcUMd9s4_bo51y8_e8OFW_hGZb",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZwwxemHcUMd9s4_bo51y8_e8OFW_hGZb",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Character Drawings",
  },
  {
    id: "6",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZuDyEoYXExvGUnETULDfEHNi3e4izy92",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZuDyEoYXExvGUnETULDfEHNi3e4izy92",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Character Drawings",
  },
  {
    id: "7",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZyoShgXZw0s3PIAlgZPhKvTjNwy3lUPA",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZyoShgXZw0s3PIAlgZPhKvTjNwy3lUPA",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Character Drawings",
  },
  {
    id: "8",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZwAj1Pd47YMssnXjIue4P1k9Tm8OYa8x",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZwAj1Pd47YMssnXjIue4P1k9Tm8OYa8x",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Character Drawings",
  },
  {
    id: "9",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZtctIObWQf15RtiCeRv7K9F65PWOEpAj",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZtctIObWQf15RtiCeRv7K9F65PWOEpAj",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Character Drawings",
  },
  {
    id: "10",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZsgnC4fttuEmj2LqxhqEWRg6z0c8koRe",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZsgnC4fttuEmj2LqxhqEWRg6z0c8koRe",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Character Drawings",
  },
  {
    id: "11",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1XlIXbEQjmO6XEXrL8rA6_WQbd_r5Zce0",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1XlIXbEQjmO6XEXrL8rA6_WQbd_r5Zce0",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "12",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1Xliw517zXoDNZUNjq220-thRONZFrdd3",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1Xliw517zXoDNZUNjq220-thRONZFrdd3",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "13",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1XyPkM3U6AmDtLuqHzZo3ZqiGPcpgw_is",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1XyPkM3U6AmDtLuqHzZo3ZqiGPcpgw_is",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "14",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1Xf7OIuqAUhq6bfKkYDetwObcTLIEKHsZ",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1Xf7OIuqAUhq6bfKkYDetwObcTLIEKHsZ",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "15",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1Xjk0PMEsTurWwpsmqPL_zUTbCJglmXjL",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1Xjk0PMEsTurWwpsmqPL_zUTbCJglmXjL",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "16",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1Xq7Kt1JQxC6MtxkDSLmhk_4eU8XsfxNi",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1Xq7Kt1JQxC6MtxkDSLmhk_4eU8XsfxNi",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "17",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1Y0fLVXjt22NzdJ1IqTCqDlm0EYNb5GBX",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1Y0fLVXjt22NzdJ1IqTCqDlm0EYNb5GBX",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "18",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1XYNPr5bW5A6jZPSAkQRKssj0Ch9JH_us",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1XYNPr5bW5A6jZPSAkQRKssj0Ch9JH_us",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "19",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1XTG3YZf0U80iH4Bk_Ft21Ccg4it_f1sL",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1XTG3YZf0U80iH4Bk_Ft21Ccg4it_f1sL",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "20",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1XOTD2pcHU894FKOfLYc__TotaEiAUp2A",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1XOTD2pcHU894FKOfLYc__TotaEiAUp2A",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "21",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1Y1IYpxXV5TS6OAPEqP8VXQ1-f5iWjqUX",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1Y1IYpxXV5TS6OAPEqP8VXQ1-f5iWjqUX",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "22",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1XJ1ByRFDri6jyHRTbqSrq54Dx_bBZtxF",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1XJ1ByRFDri6jyHRTbqSrq54Dx_bBZtxF",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "couture-design",
    subcategory: "",
  },
  {
    id: "23",
    type: "video" as const,
    src: "https://drive.google.com/file/d/1u_Nz4ZS6vJfwnyQYmpwmEc4bKQrLug0y/preview",
    thumbnail:
      "https://drive.google.com/file/d/1u_Nz4ZS6vJfwnyQYmpwmEc4bKQrLug0y/preview",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Cards",
  },
  {
    id: "24",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1uy4ZQhRjQ_akEa8ZNb-IvleR639jqX38",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1uy4ZQhRjQ_akEa8ZNb-IvleR639jqX38",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Cards",
  },
  {
    id: "25",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1uh3UkCjeIElQUo3A8YzLSyaojs69UEQf",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1uh3UkCjeIElQUo3A8YzLSyaojs69UEQf",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Cards",
  },
  {
    id: "26",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ufvyd0ZLpI2pI-oYnBwPBEaUpDkPvhlK",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ufvyd0ZLpI2pI-oYnBwPBEaUpDkPvhlK",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Cards",
  },
  {
    id: "27",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1uewzg877cT6i-Txhq6LzIEiSJyoXy1w5",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1uewzg877cT6i-Txhq6LzIEiSJyoXy1w5",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Cards",
  },
  {
    id: "28",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1uZWF92Fb2LjjboRvpL9Oc0iYMtdGUdFa",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1uZWF92Fb2LjjboRvpL9Oc0iYMtdGUdFa",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Cards",
  },
  {
    id: "29",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1uQ5gEyvpx3QdU9sL2fw-GAyoE-yLxaEi",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1uQ5gEyvpx3QdU9sL2fw-GAyoE-yLxaEi",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Cards",
  },
  {
    id: "30",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ubPlFCwA9osEFDC2xWyUC3a_1xB7qdlI",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ubPlFCwA9osEFDC2xWyUC3a_1xB7qdlI",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Cards",
  },
  {
    id: "31",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_scZlvjP1c5kvTI0BPF2llS0x9yhJPS6",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_scZlvjP1c5kvTI0BPF2llS0x9yhJPS6",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Resin Art",
  },
  {
    id: "32",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_fDeTiZPW8BOwoh5allzayQONqiIYQtT",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_fDeTiZPW8BOwoh5allzayQONqiIYQtT",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Resin Art",
  },
  {
    id: "33",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_l4Q1MXyAtf0IQkrJ7KAxtekedbfHHJk",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_l4Q1MXyAtf0IQkrJ7KAxtekedbfHHJk",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Resin Art",
  },
  {
    id: "34",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_ox_JiJcccuo86N8EA6InVh8_05FkNvM",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_ox_JiJcccuo86N8EA6InVh8_05FkNvM",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Resin Art",
  },
  {
    id: "35",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_PCvm3iZPWZB5pqJXRhvcug5iM0ftHdl",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_PCvm3iZPWZB5pqJXRhvcug5iM0ftHdl",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Resin Art",
  },
  {
    id: "36",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_XeqxfGCmzI0z_6ksLOsXXgepZKyquFJ",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_XeqxfGCmzI0z_6ksLOsXXgepZKyquFJ",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Resin Art",
  },
  {
    id: "37",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_4qcE-TxaFWeHTZPClbtl48TMJXlalNV",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_4qcE-TxaFWeHTZPClbtl48TMJXlalNV",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Resin Art",
  },
  {
    id: "38",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_7V7Iyku2Zc90acNcoza4jJyWtwunsSv",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_7V7Iyku2Zc90acNcoza4jJyWtwunsSv",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Resin Art",
  },
  {
    id: "39",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_D3DfA9zw9D3qTmFBoXP5YSNz7Gjh1iT",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_D3DfA9zw9D3qTmFBoXP5YSNz7Gjh1iT",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Resin Art",
  },
  {
    id: "40",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_O8kYsfpDG8PAHOLKi_uKRMObjLbmb34",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_O8kYsfpDG8PAHOLKi_uKRMObjLbmb34",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Resin Art",
  },
  {
    id: "41",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1a6Pkm_L88xMSSAElhXK1s-f1GJCIee5Z",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1a6Pkm_L88xMSSAElhXK1s-f1GJCIee5Z",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "craft",
    subcategory: "Resin Art",
  },
  {
    id: "42",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xMUCP8T-xWZ8ldCF-U6ruCpuapy1C7no",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xMUCP8T-xWZ8ldCF-U6ruCpuapy1C7no",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Imaginary Faces",
  },
  {
    id: "43",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xBIaKLO2CHC-iua4UPx5guACO2TF0wkZ",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xBIaKLO2CHC-iua4UPx5guACO2TF0wkZ",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Imaginary Faces",
  },
  {
    id: "44",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1x9936cNFMZymC0ltN7qiuWPdQ8fxSpxX",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1x9936cNFMZymC0ltN7qiuWPdQ8fxSpxX",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Imaginary Faces",
  },
  {
    id: "45",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1x4I1985w-G9zBqy2VVpoK8vHk26_Jwdb",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1x4I1985w-G9zBqy2VVpoK8vHk26_Jwdb",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Imaginary Faces",
  },
  {
    id: "46",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1x0571NsPsL-SV5kPRHydHUOuz7iZXthn",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1x0571NsPsL-SV5kPRHydHUOuz7iZXthn",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Imaginary Faces",
  },
  {
    id: "47",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1wynfceX0SBpUoctH3ZQJkAopx0b6HIlQ",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1wynfceX0SBpUoctH3ZQJkAopx0b6HIlQ",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Imaginary Faces",
  },
  {
    id: "48",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xAuETStwD7i9Vq-dbVyTaRYRZ21LTmGR",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xAuETStwD7i9Vq-dbVyTaRYRZ21LTmGR",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Imaginary Faces",
  },
  {
    id: "49",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xAKvjXyjLrP74x4AVe8Uj6PTPh0nIdGK",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xAKvjXyjLrP74x4AVe8Uj6PTPh0nIdGK",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Imaginary Faces",
  },
  {
    id: "50",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xYoAFp_Zcm4NskbTBNhaIKvvfK-Ut7gu",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xYoAFp_Zcm4NskbTBNhaIKvvfK-Ut7gu",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Portraiture",
  },
  {
    id: "51",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xUb_LoAjzb7TOvOrOkWrV36EUCWw7T6Z",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xUb_LoAjzb7TOvOrOkWrV36EUCWw7T6Z",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Portraiture",
  },
  {
    id: "52",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xV85k7pgVBByhasjigcvJLJN467pjoFh",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xV85k7pgVBByhasjigcvJLJN467pjoFh",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Portraiture",
  },
  {
    id: "53",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xbGnM0ZvVpBF7k16QjhYDybPU02QxDbL",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xbGnM0ZvVpBF7k16QjhYDybPU02QxDbL",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "portrait-character",
    subcategory: "Portraiture",
  },
  {
    id: "54",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xO4cFAO_K0v4hHX1N9Acvcu-eP8r-cem",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xO4cFAO_K0v4hHX1N9Acvcu-eP8r-cem",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "3D Drawings",
  },
  {
    id: "55",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZE5nNk_nr2DEzIE8gRa2wbN7pbNFm5aC",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZE5nNk_nr2DEzIE8gRa2wbN7pbNFm5aC",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "3D Drawings",
  },
  {
    id: "56",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZEXk0y9pebUcXkNahBZxwnfA5ue79mCU",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZEXk0y9pebUcXkNahBZxwnfA5ue79mCU",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "3D Drawings",
  },
  {
    id: "57",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZGEmOmBQUzARBK6gbu46xNFPxOdtnzXw",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZGEmOmBQUzARBK6gbu46xNFPxOdtnzXw",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "3D Drawings",
  },
  {
    id: "58",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZL1mUgSFcOYiBtYzKbjxqw5uuD3EPNcG",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZL1mUgSFcOYiBtYzKbjxqw5uuD3EPNcG",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "3D Drawings",
  },
  {
    id: "59",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZMufzd0jhFVQYBKdGV4VJ0zgbExCTUlO",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZMufzd0jhFVQYBKdGV4VJ0zgbExCTUlO",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "3D Drawings",
  },
  {
    id: "60",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ZTAsRhbFinxlx21ZbfBijiTKN8UlNzuJ",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ZTAsRhbFinxlx21ZbfBijiTKN8UlNzuJ",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "3D Drawings",
  },
  {
    id: "61",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xS7MWeFjv2Yb-q21ArKIkeVptu1BKFHB",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xS7MWeFjv2Yb-q21ArKIkeVptu1BKFHB",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "3D Drawings",
  },
  {
    id: "62",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xPCbAZHExIaj3O1JUyYTJ3jRx5v2MNhR",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xPCbAZHExIaj3O1JUyYTJ3jRx5v2MNhR",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "3D Drawings",
  },
  {
    id: "63",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1xPCbAZHExIaj3O1JUyYTJ3jRx5v2MNhR",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1xPCbAZHExIaj3O1JUyYTJ3jRx5v2MNhR",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "3D Drawings",
  },
  {
    id: "64",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1Yj5VdEJIU03adYY6skcNdreuTbfHe8AF",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1Yj5VdEJIU03adYY6skcNdreuTbfHe8AF",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "Brush Strokes",
  },
  {
    id: "65",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1YVWrO_Q59OHIpK6wuO6VdXwa61GHl2YQ",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1YVWrO_Q59OHIpK6wuO6VdXwa61GHl2YQ",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "Brush Strokes",
  },
  {
    id: "66",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1YMj0PyssmqjahiYdeDeFcWxDMY71w7-F",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1YMj0PyssmqjahiYdeDeFcWxDMY71w7-F",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "Brush Strokes",
  },
  {
    id: "67",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1YSCiUwwAtEBDTrVOIpelUYsWtQ0cbS27",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1YSCiUwwAtEBDTrVOIpelUYsWtQ0cbS27",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "Brush Strokes",
  },
  {
    id: "68",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1YBMQhmCn2MZa_O-WIqw3_sE25fYCdGef",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1YBMQhmCn2MZa_O-WIqw3_sE25fYCdGef",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "Brush Strokes",
  },
  {
    id: "69",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1YJXx_W5r5lbjQvaDwO_lkqaxzQ_f47lD",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1YJXx_W5r5lbjQvaDwO_lkqaxzQ_f47lD",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "Brush Strokes",
  },
  {
    id: "70",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1YJ0vpo34YWlRIFmTmzGDszziR4-GyfXe",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1YJ0vpo34YWlRIFmTmzGDszziR4-GyfXe",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "Brush Strokes",
  },
  {
    id: "71",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1YkIt2OppDidLeKfC_7Tlr9BI9wkoNPRL",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1YkIt2OppDidLeKfC_7Tlr9BI9wkoNPRL",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "Brush Strokes",
  },
  {
    id: "72",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1YodhcThklMnviPAAQdH5wgm0JVOddCPd",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1YodhcThklMnviPAAQdH5wgm0JVOddCPd",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "Brush Strokes",
  },
  {
    id: "73",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1YRT-hHKt3n7bqJNUw8DeAQlca95n1j09",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1YRT-hHKt3n7bqJNUw8DeAQlca95n1j09",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "Brush Strokes",
  },
  {
    id: "74",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1YbtyDQPclLCy4Dps8WREiqto7HVHKUbq",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1YbtyDQPclLCy4Dps8WREiqto7HVHKUbq",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "painting-drawing",
    subcategory: "Brush Strokes",
  },
];
