export const workItems = [
  {
    id: "6",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=18GdlzWFtu1ojWymZT0bjLHEMPbJq2eis",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=18GdlzWFtu1ojWymZT0bjLHEMPbJq2eis",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "7",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1adCUVcfXMPYj6IDC7vQBjvaA134-JFaE",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1adCUVcfXMPYj6IDC7vQBjvaA134-JFaE",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "8",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1fRYc5Wp8U9WkmfE570duerJiTbyQ_AUg",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1fRYc5Wp8U9WkmfE570duerJiTbyQ_AUg",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "9",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1v1uifSQoHMLxAb9hifkc800XibB5HTa3",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1v1uifSQoHMLxAb9hifkc800XibB5HTa3",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "10",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1COuG2QBI8iXEWPPmQfqGEuZpiR8dOeHc",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1COuG2QBI8iXEWPPmQfqGEuZpiR8dOeHc",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "11",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=11T0xaW6sSGLNSdvFG8exPp-JIJZ0Xa6j",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=11T0xaW6sSGLNSdvFG8exPp-JIJZ0Xa6j",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "12",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=10e58n3_DHM2Rk6mB-RzSXLzitFzNwMak",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=10e58n3_DHM2Rk6mB-RzSXLzitFzNwMak",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "13",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1YGrcKeDG4OTrgoOYvbPwwCK1mN0hXJEX",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1YGrcKeDG4OTrgoOYvbPwwCK1mN0hXJEX",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "14",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1_zLeC6LtIEpXbdJ8ksnXx0-iCaOeA30a",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1_zLeC6LtIEpXbdJ8ksnXx0-iCaOeA30a",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "15",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1um9zYKrUkNJOigk36-1TFdFfWK3eu-3q",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1um9zYKrUkNJOigk36-1TFdFfWK3eu-3q",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "16",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1Z3fvlXpHCZgO1g0d95pP8TcENfn7RIb2",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1Z3fvlXpHCZgO1g0d95pP8TcENfn7RIb2",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "17",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1RZiZyRjwr__xqQFztH7povwhp5ByiSqr",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1RZiZyRjwr__xqQFztH7povwhp5ByiSqr",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "18",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1LevJZ1B24O2op-c4G_OFsmtVGk_YJBQC",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1LevJZ1B24O2op-c4G_OFsmtVGk_YJBQC",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "19",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1R9C6OZywUVtDHMJJTYhPrBB2LbuRm7I1",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1R9C6OZywUVtDHMJJTYhPrBB2LbuRm7I1",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "20",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1DKm9WU4Bc2YFlTMR-N9x5Whcw5TNByt8",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1DKm9WU4Bc2YFlTMR-N9x5Whcw5TNByt8",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "21",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1JusPHp5yMd2Ink8GTyAx351eccwIVLdt",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1JusPHp5yMd2Ink8GTyAx351eccwIVLdt",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "22",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1e_6hdWEBHvNYA9gyrFPkKL55uYQRoLxC",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1e_6hdWEBHvNYA9gyrFPkKL55uYQRoLxC",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "23",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1lcqM_8r9HnxXr4PAyfekXuwzbQoCaZHU",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1lcqM_8r9HnxXr4PAyfekXuwzbQoCaZHU",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "24",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1wOAhGw_pV6BfdEsD6b0dEuGUMDyAz-dZ",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1wOAhGw_pV6BfdEsD6b0dEuGUMDyAz-dZ",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "25",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1JrwjIZmCmRzHWtYfADzJ0osfUgqj0YB1",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1JrwjIZmCmRzHWtYfADzJ0osfUgqj0YB1",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "26",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1kWDC0Fma8KEx3Ly45B3OIGdv2tFKae8d",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1kWDC0Fma8KEx3Ly45B3OIGdv2tFKae8d",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "27",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1ecYM4IMhYtR8fv87C2Mfvv9yaE1H6bDU",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1ecYM4IMhYtR8fv87C2Mfvv9yaE1H6bDU",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "28",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1jYl8OTJHtacQhYqNoY70lpuBTTA6bMbf",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1jYl8OTJHtacQhYqNoY70lpuBTTA6bMbf",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "29",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1V4hra5MmT3vV8IL4mkbULwOVb-OhhT3Y",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1V4hra5MmT3vV8IL4mkbULwOVb-OhhT3Y",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "30",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1FtYXYH1M9oVcPi0hQKEqc4Nzq2Ol78ez",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1FtYXYH1M9oVcPi0hQKEqc4Nzq2Ol78ez",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "31",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1vrd8tUrVingD-OcvSsF55NsNw-mEqZh0",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1vrd8tUrVingD-OcvSsF55NsNw-mEqZh0",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "32",
    type: "image" as const,
    src: "https://drive.google.com/uc?export=view&id=1UR5VlZaBarLnDoCrBrwREddVUi6tVFFy",
    thumbnail:
      "https://drive.google.com/uc?export=view&id=1UR5VlZaBarLnDoCrBrwREddVUi6tVFFy",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "illustration",
    subcategory: "Digital 2D",
  },
  {
    id: "1",
    type: "video" as const,
    src: "https://drive.google.com/file/d/1pSaCM0rnQnhofw5O9B0x8tGDgr8R12w_/preview",
    thumbnail:
      "https://drive.google.com/file/d/1pSaCM0rnQnhofw5O9B0x8tGDgr8R12w_/preview",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "animation",
    subcategory: "Digital 2D",
  },
  {
    id: "2",
    type: "video" as const,
    src: "https://drive.google.com/file/d/1pLqMo1QpddXDwDXiE1oIDpqg-laOJ-E0/preview",
    thumbnail:
      "https://drive.google.com/file/d/1pLqMo1QpddXDwDXiE1oIDpqg-laOJ-E0/preview",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "animation",
    subcategory: "Digital 2D",
  },
  {
    id: "3",
    type: "video" as const,
    src: "https://drive.google.com/file/d/1pJ3OhmqWTnmmLbVdL33L_CIKREYegfAG/preview",
    thumbnail:
      "https://drive.google.com/file/d/1pJ3OhmqWTnmmLbVdL33L_CIKREYegfAG/preview",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "animation",
    subcategory: "Digital 2D",
  },
  {
    id: "4",
    type: "video" as const,
    src: "https://drive.google.com/file/d/1pLw1XmsvQlF6DieUSMEp3kyYM_VZXn7h/preview",
    thumbnail:
      "https://drive.google.com/file/d/1pLw1XmsvQlF6DieUSMEp3kyYM_VZXn7h/preview",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "animation",
    subcategory: "Digital 2D",
  },
  {
    id: "5",
    type: "video" as const,
    src: "https://drive.google.com/file/d/1seyQt9SpsAmrB5J-HAwwrxq0EG2qaQ-e/preview",
    thumbnail:
      "https://drive.google.com/file/d/1seyQt9SpsAmrB5J-HAwwrxq0EG2qaQ-e/preview",
    title: "Character Animation",
    description: "A dynamic character animation sequence",
    category: "animation",
    subcategory: "Digital 2D",
  },
];
